import {
  BusinessProfile,
  Competitor,
  WebsiteAnalysis,
  GBPAnalysis,
  WebsiteMetadata,
} from "./types";

// Self GBP Data - Full data from the provided sample
export const MOCK_BUSINESS: BusinessProfile = {
  title: "Garrison Orthodontics - Dr. Garrison Copeland",
  price: null,
  categoryName: "Orthodontist",
  address: "300 Executive Dr Suite 365, West Orange, NJ 07052",
  neighborhood: null,
  street: "300 Executive Dr Suite 365",
  city: "West Orange",
  postalCode: "07052",
  state: "New Jersey",
  countryCode: "US",
  website: "https://www.garrisonorthodontics.com/",
  phone: "(862) 451-8117",
  phoneUnformatted: "+18624518117",
  claimThisBusiness: false,
  location: {
    lat: 40.7964763,
    lng: -74.2613414,
  },
  plusCode: "QPWQ+HF West Orange, New Jersey",
  totalScore: 5,
  permanentlyClosed: false,
  temporarilyClosed: false,
  placeId: "ChIJPyWNjkKrw4kRqdcbfNW8d9k",
  categories: ["Orthodontist", "Dental clinic", "Dentist"],
  fid: "0x89c3ab428e8d253f:0xd977bcd57c1bd7a9",
  cid: "15670201053555185577",
  reviewsCount: 62,
  reviewsDistribution: {
    oneStar: 0,
    twoStar: 0,
    threeStar: 0,
    fourStar: 0,
    fiveStar: 62,
  },
  imagesCount: 24,
  imageCategories: ["All", "By owner"],
  url: "https://www.google.com/maps/search/?api=1&query=Garrison%20Orthodontics%20-%20Dr.%20Garrison%20Copeland&query_place_id=ChIJPyWNjkKrw4kRqdcbfNW8d9k",
  searchPageUrl:
    "https://www.google.com/maps/search/Garrison%20Orthodontics,%20West%20Orange,%20NJ?hl=en",
  searchString: "Garrison Orthodontics, West Orange, NJ",
  language: "en",
  rank: 1,
  isAdvertisement: false,
  imageUrl:
    "https://lh3.googleusercontent.com/p/AF1QipNilVCGRGuNmq0BEfoulSr6WZipBjEQZzskMcaO=w426-h240-k-no",
  kgmid: "/g/11wq7wgxg1",
  openingHours: [
    { day: "Monday", hours: "10 AM to 8 PM" },
    { day: "Tuesday", hours: "10 AM to 6 PM" },
    { day: "Wednesday", hours: "10 AM to 6 PM" },
    { day: "Thursday", hours: "10 AM to 8 PM" },
    { day: "Friday", hours: "10 AM to 6 PM" },
    { day: "Saturday", hours: "10 AM to 1 PM" },
    { day: "Sunday", hours: "9 AM to 6 PM" },
  ],
  peopleAlsoSearch: [
    {
      category: "People also search for",
      title: "Garrison Copeland",
      reviewsCount: 0,
      totalScore: 0,
    },
    {
      category: "People also search for",
      title: "Milestone Orthodontics",
      reviewsCount: 160,
      totalScore: 4.8,
    },
    {
      category: "People also search for",
      title: "Dr. Kevin B. Persily, DDS",
      reviewsCount: 1,
      totalScore: 5,
    },
    {
      category: "People also search for",
      title: "CreatingSmiles",
      reviewsCount: 165,
      totalScore: 4.7,
    },
    {
      category: "People also search for",
      title: "Millburn Orthodontics",
      reviewsCount: 25,
      totalScore: 4.7,
    },
  ],
  reviewsTags: [
    { title: "attention", count: 4 },
    { title: "state of the art", count: 2 },
    { title: "expertise", count: 2 },
    { title: "the office", count: 2 },
    { title: "desire", count: 2 },
    { title: "gap", count: 2 },
    { title: "remarkable", count: 2 },
    { title: "sports", count: 2 },
    { title: "empathy", count: 2 },
    { title: "choice", count: 2 },
  ],
  additionalInfo: {
    "From the business": [{ "Identifies as Black-owned": true }],
    "Service options": [{ English: true }],
    Accessibility: [
      { "Wheelchair accessible entrance": true },
      { "Wheelchair accessible parking lot": true },
      { "Wheelchair accessible restroom": true },
    ],
    Amenities: [{ Restroom: true }],
    Planning: [
      { "Appointment required": true },
      { "Appointments recommended": true },
    ],
    Payments: [
      { "Credit cards": true },
      { "Debit cards": true },
      { "NFC mobile payments": true },
    ],
    Parking: [{ "Free parking lot": true }, { "On-site parking": true }],
  },
  bookingLinks: [
    {
      name: "garrisonorthodontics.com",
      url: "https://www.garrisonorthodontics.com/contact/",
    },
  ],
  ownerUpdates: [
    {
      text: "Garrison Orthodontics provides interceptive orthodontics in West Orange, NJ to identify and correct developing dental issues early. Our proactive treatments help guide proper jaw growth, create space for incoming teeth, and reduce the need for more complex orthodontic care later. We focus on timely, gentle solutions for growing smiles.\n\n",
      buttonText: "Call now",
      buttonLink: null,
      date: "2026-01-07T10:50:33.000Z",
      imageUrl:
        "https://lh3.googleusercontent.com/geougc/AF1QipMr9VHGyxB7QDnWzEV1v8EtBQApyinXlqoDirWD=h400-no",
    },
    {
      text: "Garrison Orthodontics offers pediatric tooth extraction in West Orange, NJ with a gentle, child-focused approach. Our experienced team ensures safe, comfortable extractions to support healthy dental development and proper orthodontic alignment. We prioritize pain control, clear communication, and a stress-free experience for both children and parents.\n\n",
      buttonText: "Call now",
      buttonLink: null,
      date: "2026-01-07T10:49:21.000Z",
      imageUrl:
        "https://lh3.googleusercontent.com/geougc/AF1QipPYugNOLlYDwcZInaSBkunmocdyWvM2BfmbDSHG=h400-no",
    },
    {
      text: "Garrison Orthodontics provides professional orthodontic spacers in West Orange, NJ to prepare teeth for effective brace placement. These small devices create proper space between teeth, helping ensure accurate band fitting and smoother orthodontic treatment. Our experienced team focuses on gentle care and precise planning to support successful, comfortable orthodontic outcomes.\n\n",
      buttonText: "Call now",
      buttonLink: null,
      date: "2026-01-05T05:34:19.000Z",
      imageUrl:
        "https://lh3.googleusercontent.com/geougc/AF1QipMLowK8exhlxNT85lPgbgHLY6QGwS3cPWcBZEjY=h400-no",
    },
    {
      text: "Garrison Orthodontics offers advanced self-ligating braces in West Orange, NJ for patients seeking faster, more comfortable orthodontic treatment. These modern braces reduce friction, require fewer adjustments, and help improve overall treatment efficiency. Our experienced orthodontic team provides personalized care to ensure optimal alignment, bite correction, and long-lasting results.\n\n",
      buttonText: "Call now",
      buttonLink: null,
      date: "2026-01-05T05:33:29.000Z",
      imageUrl:
        "https://lh3.googleusercontent.com/geougc/AF1QipPzLUz1NwmKZciE2HEDe08mbYAV_StOpmDhaqKJ=h400-no",
    },
    {
      text: "Garrison Orthodontics offers expert Invisalign treatment in West Orange, NJ for patients seeking a discreet and comfortable way to straighten teeth. Our custom clear aligners correct bite and alignment issues while fitting seamlessly into your lifestyle. Enjoy personalized orthodontic care for a confident, healthy smile.\n\n",
      buttonText: "Call now",
      buttonLink: null,
      date: "2025-12-23T10:21:17.000Z",
      imageUrl:
        "https://lh3.googleusercontent.com/geougc/AF1QipOlrxNZhJKfptVJqrMADLKSTnJgF3z4szH9OIc-=h400-no",
    },
  ],
  imageUrls: [
    "https://lh3.googleusercontent.com/p/AF1QipNilVCGRGuNmq0BEfoulSr6WZipBjEQZzskMcaO=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzubtAFW-Fqfg_lOf4aIbdttK8rpu3UDLi_jg3-ZlJi_GuFcftMcNLzrTLQkhcLQOFs6BttUdzSRkZhsz1fiBHhPScgHYz8wAL4z34oUEkerUbZb-DCoZThgtrqwriRVUxmrBaj-jzT53o=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyhlnUbvn-h6sbsW5Ip1aRVHn3zOBH33ad4Wru61waObEx90BofXuMMxAqnM-Aqa11WwfQUsMh4eKO_PJok0yErOc9uCiSfkQo0u5JIjP5pU_g_e1u8e40g0mxo6Qh4E2gvGSJT=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz4-_1cJ4QLona-pdhxRReYMWgPVFi4OAFXZKl-yO7-iDz6CvvmyGzH_LMK9mVG9pEm2tVzu6zzOcm5xDRD5bOrNJGBCGBRvahUi3wkem7C08KQFvTqtqqODLwNex_eHV9lMPoC=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxDch-gJVFonOcbr0CxWJzldeyF57nC8v-U0SihOIFlx1UnzY1dyX5LRZHYUfT-Lf7dw6huPFwH_dv_la_SVO6odVcDPGnNXrPjzjE6GJXpecpmlAIdnPfQZtu5sKYoPM9nkWRXIc1jrgCN=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/p/AF1QipNCan6P4tZdZ9bX5TiF7cZMLYM7RJ8HQQMCiDuI=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzf-L9R5AGYDAevBuBI6ATMqoCgwa_dIK4ukPUurrgUf9SrlxahBRXFWv0TJ6Y7I9v-_MM8liaTZMZbVlb-Qi41KY3aLR6L6zmYistIrr84wkqHMMUmJig2eiFlu9blP8aMEs0=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSydMuDwb0d1vsF53zeU1l14kgcrQhdAtqKBWeUqKPgk8dMMQPDmVnX859-gjH0iiyBMJxwhyEoNsqlRH9XywQa-3Y8SHTLcNI4Kxg0JSi9Ig8x6EzTXS17XBrsbis1KluBEl-OAl9AMitA=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyomf3JpTdDeGV08kFymVHSa6Dpb9gYc-8fBB9KtyujJJ4ZIjdCIsoq4Lkvmv7qlhyOWD3Jxm2-8dif_-glVEIImLxjoHyjvW9Z5bV4Vx3Ut5ip91xoBvh4XyhA66U09cjt_kE=w1920-h1080-k-no",
    "https://lh3.googleusercontent.com/p/AF1QipPIUgfYT7D08v5TXkQQDPEb2ZDXWEOaU4yhLfYn=w1920-h1080-k-no",
  ],
  reviews: [
    {
      reviewerId: "103609618111221716946",
      reviewerUrl:
        "https://www.google.com/maps/contrib/103609618111221716946?hl=en",
      name: "Richard Osagie",
      reviewerNumberOfReviews: 8,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a/ACg8ocISCpxI3sYSXVmauhkX5uQyKfMkZjQ3teKeWk-5xlde5sNepg=s1920-c-rp-mo-br100",
      text: "Dr C is awesome! He always strives to make sure that I achieve the perfect smile. Valerie is awesome too! Definitely the best Orthodontist office I've been to in a while. Highly recommend.",
      textTranslated: null,
      publishAt: "a week ago",
      publishedAtDate: "2025-12-30T20:41:17.897Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT25KSWQwdE1laTFPUkVKb1NXeHBaMnBGYzBOM1pGRRAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT25KSWQwdE1laTFPUkVKb1NXeHBaMnBGYzBOM1pGRRAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOnJId0tMei1OREJoSWxpZ2pFc0N3ZFE%7C0dK2YhpTEw1%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-12-30T23:41:11.000Z",
      responseFromOwnerText:
        "Hi, Richard. We appreciate the kind words and are glad we could provide you with a positive experience!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: "en",
      translatedLanguage: null,
    },
    {
      reviewerId: "110751184881674620328",
      reviewerUrl:
        "https://www.google.com/maps/contrib/110751184881674620328?hl=en",
      name: "Alesha Simmons",
      reviewerNumberOfReviews: 4,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a/ACg8ocKjY7BhMIWWQoR6MhIwrsEuzJYYHhpFTjOI4bJlNIS7f3xtxQ=s1920-c-rp-mo-br100",
      text: "Dr. Garrison is amazing. He explains everything he's about to do. I love how fast he is. The staff is amazing as well. I highly recommend.",
      textTranslated: null,
      publishAt: "3 weeks ago",
      publishedAtDate: "2025-12-20T10:54:02.002Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT2xkdlh6TlhaMWRpWDBSeFMxTTVObUZWVTJoaGFuYxAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2xkdlh6TlhaMWRpWDBSeFMxTTVObUZWVTJoaGFuYxAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOldvXzNXZ1diX0RxS1M5NmFVU2hhanc%7C0dGc09-9M87%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-12-20T12:53:10.000Z",
      responseFromOwnerText:
        "Hi, Alesha. Thanks for taking the time to share your positive experience. We truly appreciate it!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: "en",
      translatedLanguage: null,
    },
    {
      reviewerId: "105464334102736364684",
      reviewerUrl:
        "https://www.google.com/maps/contrib/105464334102736364684?hl=en",
      name: "Tatianna Exius",
      reviewerNumberOfReviews: 4,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a-/ALV-UjValhFCmNM2_0dzFYAZTYgUbwG3YbWB3moQJHQEmye5WNboOVgt=s1920-c-rp-mo-br100",
      text: "Thankful to have found Garrison Orthodontics. Dr. Copeland was incredibly gentle and thorough in explaining my treatment plan, and the front desk greeted me with such a warm welcome. I truly appreciate the care and professionalism of the entire team.",
      textTranslated: null,
      publishAt: "a month ago",
      publishedAtDate: "2025-12-10T06:11:10.430Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT21aU2VEUTJhamxrZFZFM2FHdENUR1J3UmxoaFEzYxAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21aU2VEUTJhamxkZFZFM2FHdENUR1J3UmxoaFEzYxAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOmZSeDQ2ajlkdVE3aGtCTGRwRlhhQ3c%7C0dDFvyOeIAy%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-12-10T08:17:11.000Z",
      responseFromOwnerText:
        "Hi, Tatianna. We are thrilled to learn that you had a positive experience with us!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: "en",
      translatedLanguage: null,
    },
    {
      reviewerId: "103321516460632801723",
      reviewerUrl:
        "https://www.google.com/maps/contrib/103321516460632801723?hl=en",
      name: "Amari Ritchards",
      reviewerNumberOfReviews: 2,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a/ACg8ocI8v4VZ7cq46ERRgDRPddk3jUykMY6koQoLikhVMIhGMIlHExig=s1920-c-rp-mo-br100",
      text: null,
      textTranslated: null,
      publishAt: "2 months ago",
      publishedAtDate: "2025-11-06T05:21:24.505Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT2twcE4yMHRlbVk0U0V3MVUwRTFPWGhqWmtGM1FuYxAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT2twcE4yMHRlbVk0U0V3MVUwRTFPWGhqWmtGM1FuYxAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOkppN20temY4SEw1U0E1OXhjZkF3Qnc%7C0d220JT74vA%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-11-06T07:27:08.000Z",
      responseFromOwnerText:
        "Hi, Amari. We appreciate the rating, and are glad we could provide you with a positive experience!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: null,
      translatedLanguage: null,
    },
    {
      reviewerId: "107993209557568117570",
      reviewerUrl:
        "https://www.google.com/maps/contrib/107993209557568117570?hl=en",
      name: "Sheffield Marcus",
      reviewerNumberOfReviews: 4,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a/ACg8ocKaKDJkJfzv0e-uQrhDGQQjlYYaEJxKHP-yrRl7ZjlU-7OSTg=s1920-c-rp-mo-br100",
      text: "Office was clean and modern. Staff was friendly and informative. Dr. Copeland was straightforward and honest about my evaluation. Definitely would recommend!",
      textTranslated: null,
      publishAt: "2 months ago",
      publishedAtDate: "2025-10-31T22:41:51.512Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT21ReGJ6RlRkRlZrVWpGRFMxQlZWbGxxZEVWMk1sRRAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21ReGJ6RlRkRlZrVWpGRFMxQlZWbGxxZEVWMk1sRRAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOmQxbzFTdFVkUjFDS1BVVllqdEV2MlE%7C0d0IgjTWyQb%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-11-01T00:48:08.000Z",
      responseFromOwnerText:
        "Hi, Sheffield. We appreciate the kind words and are glad we could provide you with a positive experience!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: "en",
      translatedLanguage: null,
    },
    {
      reviewerId: "107448906365380872088",
      reviewerUrl:
        "https://www.google.com/maps/contrib/107448906365380872088?hl=en",
      name: "Dajah Moena",
      reviewerNumberOfReviews: 4,
      isLocalGuide: false,
      reviewerPhotoUrl:
        "https://lh3.googleusercontent.com/a/ACg8ocK_Eoro8s-cUUa5KTiY2pPVdHOw-iOVePVTlNVJdGuIql6HsQ=s1920-c-rp-mo-br100",
      text: "⭐⭐⭐⭐⭐\nAs a first-time braces patient I was nervous, but the moment I walked into the office I felt at ease. The facility is modern, beautiful and spotless... Dr. Copeland explained everything thoroughly and made me feel comfortable with the process. I'm so glad I chose this place- highly recommend!",
      textTranslated: null,
      publishAt: "3 months ago",
      publishedAtDate: "2025-09-19T19:11:54.089Z",
      likesCount: 0,
      reviewId:
        "Ci9DQUlRQUNvZENodHljRjlvT21wd01XNXBVbUZZTW1wUlduZEtVVkJyUmxWNWQwRRAB",
      reviewUrl:
        "https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21wd01XNXBVbUZZTW1wUlduZEtVVkJyUmxWNWQwRRAB!2m1!1s0x0:0xd977bcd57c1bd7a9!3m1!1s2@1:CAIQACodChtycF9oOmpwMW5pUmFYMmpRWndKUVBrRlV5d0E%7C0cnPfu4JshJ%7C?hl=en",
      reviewOrigin: "Google",
      stars: 5,
      rating: null,
      responseFromOwnerDate: "2025-09-19T21:16:10.000Z",
      responseFromOwnerText:
        "Hi, Dajah. Thank you so much for leaving us a stellar review!",
      reviewImageUrls: [],
      reviewContext: {},
      reviewDetailedRating: {},
      visitedIn: null,
      originalLanguage: "en",
      translatedLanguage: null,
    },
  ],
};

// Competitor Data - Full data from the provided sample
export const MOCK_COMPETITORS: Competitor[] = [
  {
    title: "My Orthodontist - West Orange",
    price: null,
    categoryName: "Orthodontist",
    address: "443 Northfield Ave # 101, West Orange, NJ 07052",
    neighborhood: null,
    street: "443 Northfield Ave # 101",
    city: "West Orange",
    postalCode: "07052",
    state: "New Jersey",
    countryCode: "US",
    website: "https://luvmyorthodontist.com/",
    phone: "(973) 672-4141",
    phoneUnformatted: "+19736724141",
    claimThisBusiness: false,
    location: { lat: 40.7716844, lng: -74.2708114 },
    totalScore: 4.7,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: "ChIJk_FJM6lUwokRJ_ijVRJ8tik",
    categories: ["Orthodontist"],
    fid: "0x89c254a93349f193:0x29b67c1255a3f827",
    cid: "3005726219504449575",
    reviewsCount: 398,
    imagesCount: 219,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "9 AM to 5:30 PM" },
      { day: "Wednesday", hours: "Closed" },
      { day: "Thursday", hours: "9 AM to 5:30 PM" },
      { day: "Friday", hours: "9 AM to 5:30 PM" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    additionalInfo: {
      "Service options": [{ English: true }],
      Accessibility: [
        { "Wheelchair accessible entrance": true },
        { "Wheelchair accessible parking lot": true },
        { "Wheelchair accessible restroom": true },
      ],
      Amenities: [{ Restroom: true }],
      Planning: [{ "Appointments recommended": true }],
      Payments: [
        { "Credit cards": true },
        { "Debit cards": true },
        { "NFC mobile payments": true },
      ],
    },
    url: "https://www.google.com/maps/search/?api=1&query=My%20Orthodontist%20-%20West%20Orange&query_place_id=ChIJk_FJM6lUwokRJ_ijVRJ8tik",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 1,
    isAdvertisement: false,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipMiEUXfan-YmCWRM-dltOi2jzpmJ0v7-rptNvFr=w408-h406-k-no",
    kgmid: "/g/11bz_474gb",
  },
  {
    title: "Newman Orthodontics; West Orange Location",
    price: null,
    categoryName: "Orthodontist",
    address: "395 Pleasant Valley Way, West Orange, NJ 07052",
    neighborhood: null,
    street: "395 Pleasant Valley Way",
    city: "West Orange",
    postalCode: "07052",
    state: "New Jersey",
    countryCode: "US",
    website: "https://www.newmanortho.com/",
    phone: "(973) 731-5855",
    phoneUnformatted: "+19737315855",
    claimThisBusiness: false,
    location: { lat: 40.8128433, lng: -74.2595672 },
    totalScore: 5,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: "ChIJi4hVu_Sqw4kR-x9UiFaAsNI",
    categories: ["Orthodontist"],
    fid: "0x89c3aaf4bb55888b:0xd2b0805688541ffb",
    cid: "15181775453008699387",
    reviewsCount: 192,
    imagesCount: 29,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "9 AM to 5 PM" },
      { day: "Tuesday", hours: "9 AM to 5 PM" },
      { day: "Wednesday", hours: "9 AM to 5 PM" },
      { day: "Thursday", hours: "2 to 7 PM" },
      { day: "Friday", hours: "9 AM to 5 PM" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    additionalInfo: {
      Accessibility: [
        { "Wheelchair accessible entrance": true },
        { "Wheelchair accessible parking lot": true },
        { "Wheelchair accessible restroom": true },
      ],
      Amenities: [{ Restroom: true }],
      Planning: [{ "Appointments recommended": true }],
      Payments: [
        { "Credit cards": true },
        { "Debit cards": true },
        { "NFC mobile payments": true },
      ],
      Parking: [{ "Free parking lot": true }, { "On-site parking": true }],
    },
    url: "https://www.google.com/maps/search/?api=1&query=Newman%20Orthodontics%3B%20West%20Orange%20Location&query_place_id=ChIJi4hVu_Sqw4kR-x9UiFaAsNI",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 2,
    isAdvertisement: false,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipO7FsgZpTw1eUV--8UYJlGDo61rViLidJWtkExW=w408-h543-k-no",
    kgmid: "/g/1tkkvtqj",
  },
  {
    title: "Milestone Orthodontics",
    price: null,
    categoryName: "Orthodontist",
    address: "502 Pleasant Valley Way, West Orange, NJ 07052",
    neighborhood: null,
    street: "502 Pleasant Valley Way",
    city: "West Orange",
    postalCode: "07052",
    state: "New Jersey",
    countryCode: "US",
    website: "https://www.milestoneorthodontics.com/",
    phone: "(973) 325-1777",
    phoneUnformatted: "+19733251777",
    claimThisBusiness: false,
    location: { lat: 40.8087835, lng: -74.2607315 },
    totalScore: 4.8,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: "ChIJT1AZn_aqw4kRNnm52q4Uex8",
    categories: ["Orthodontist"],
    fid: "0x89c3aaf69f19504f:0x1f7b14aedab97936",
    cid: "2268429578537630006",
    reviewsCount: 160,
    imagesCount: 30,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "9 AM to 7 PM" },
      { day: "Tuesday", hours: "9 AM to 7 PM" },
      { day: "Wednesday", hours: "9 AM to 5 PM" },
      { day: "Thursday", hours: "9 AM to 7 PM" },
      { day: "Friday", hours: "Closed" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    additionalInfo: {
      "Service options": [{ "Onsite services": true }],
      Accessibility: [{ "Wheelchair accessible parking lot": true }],
      Amenities: [{ Restroom: true }],
      Planning: [{ "Appointments recommended": true }],
      Payments: [
        { "Credit cards": true },
        { "Debit cards": true },
        { "NFC mobile payments": true },
      ],
    },
    url: "https://www.google.com/maps/search/?api=1&query=Milestone%20Orthodontics&query_place_id=ChIJT1AZn_aqw4kRNnm52q4Uex8",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 3,
    isAdvertisement: false,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipPDWSzRNyRVZ9FsCAiyxnT1foT1bytG5G-XsEzo=w408-h506-k-no",
    kgmid: "/g/1td0hfrv",
  },
  {
    title: "Sacks Orthodontics",
    price: null,
    categoryName: "Orthodontist",
    address: "41 North Livingston Avenue, Livingston, NJ 07039-2112",
    neighborhood: null,
    street: "41 North Livingston Avenue",
    city: "Livingston",
    postalCode: "07039-2112",
    state: "New Jersey",
    countryCode: "US",
    website: "",
    phone: "(973) 251-2265",
    phoneUnformatted: "+1 973-251-2265",
    claimThisBusiness: false,
    location: { lat: 40.797318, lng: -74.315969 },
    totalScore: 5,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: null,
    categories: ["Orthodontist"],
    fid: "0x89c3abd5db342f63:0x23ed8dcaec0545b9",
    cid: "2588881263490581945",
    reviewsCount: 740,
    imagesCount: null,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "9 AM to 5 PM" },
      { day: "Tuesday", hours: "9 AM to 6 PM" },
      { day: "Wednesday", hours: "10 AM to 6 PM" },
      { day: "Thursday", hours: "9 AM to 5 PM" },
      { day: "Friday", hours: "8 AM to 4 PM" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    url: "https://www.google.com/maps/place/Sacks Orthodontics/@40.797318,-74.315969,14z/data=!3m1!4b1!4m9!3m8!5m2!4m1!1i2!8m2!3d40.797318!4d-74.315969!16snull!17Bnull",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 21,
    isAdvertisement: true,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipPhRWOPTf1_YNgty3ejY5qWwGOF9Cc69N_YQuEW=k-no-",
    kgmid: null,
  },
  {
    title: "D&G Dental of West Orange",
    price: null,
    categoryName: "Dentist",
    address: "667 Eagle Rock Ave 2nd Floor, West Orange, NJ 07052",
    neighborhood: null,
    street: "667 Eagle Rock Ave 2nd Floor",
    city: "West Orange",
    postalCode: "07052",
    state: "New Jersey",
    countryCode: "US",
    website: "https://www.dgdental.com/",
    phone: "(973) 731-2200",
    phoneUnformatted: "+19737312200",
    claimThisBusiness: false,
    location: { lat: 40.8107374, lng: -74.2615202 },
    totalScore: 4.9,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: "ChIJj4AUSfSqw4kR9N3SkroO_Gw",
    categories: [
      "Dentist",
      "Cosmetic dentist",
      "Dental implants provider",
      "Denture care center",
      "Emergency dental service",
      "Teeth whitening service",
    ],
    fid: "0x89c3aaf44914808f:0x6cfc0eba92d2ddf4",
    cid: "7853168044717301236",
    reviewsCount: 825,
    reviewsDistribution: {
      oneStar: 6,
      twoStar: 2,
      threeStar: 1,
      fourStar: 16,
      fiveStar: 800,
    },
    imagesCount: 41,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "9:30 AM to 6 PM" },
      { day: "Tuesday", hours: "9:30 AM to 6 PM" },
      { day: "Wednesday", hours: "9:30 AM to 6 PM" },
      { day: "Thursday", hours: "9:30 AM to 6 PM" },
      { day: "Friday", hours: "9:30 AM to 4 PM" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    additionalInfo: {
      Accessibility: [
        { "Wheelchair accessible entrance": true },
        { "Wheelchair accessible parking lot": true },
        { "Wheelchair accessible restroom": true },
      ],
      Amenities: [{ Restroom: true }],
      Planning: [
        { "Appointment required": true },
        { "Appointments recommended": true },
      ],
      Payments: [
        { "Credit cards": true },
        { "Debit cards": true },
        { "NFC mobile payments": true },
      ],
    },
    url: "https://www.google.com/maps/search/?api=1&query=D%26G%20Dental%20of%20West%20Orange&query_place_id=ChIJj4AUSfSqw4kR9N3SkroO_Gw",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 26,
    isAdvertisement: false,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipN14wVblzuSYxx-LSpZxY_TOrU-fDcHxLIjr7vV=w408-h272-k-no",
    kgmid: "/g/1pp2v09hq",
  },
  {
    title: "Supreme Dental Associates",
    price: null,
    categoryName: "Dentist",
    address: "331 Valley Rd, West Orange, NJ 07052",
    neighborhood: null,
    street: "331 Valley Rd",
    city: "West Orange",
    postalCode: "07052",
    state: "New Jersey",
    countryCode: "US",
    website: "http://www.supremedentalassociates.com/",
    phone: "(973) 325-9800",
    phoneUnformatted: "+19733259800",
    claimThisBusiness: false,
    location: { lat: 40.7760167, lng: -74.2397042 },
    totalScore: 4.2,
    permanentlyClosed: false,
    temporarilyClosed: false,
    placeId: "ChIJO_gNcz6rw4kRLrhzDMmCnwQ",
    categories: ["Dentist"],
    fid: "0x89c3ab3e730df83b:0x49f82c90c73b82e",
    cid: "333128697457653806",
    reviewsCount: 223,
    reviewsDistribution: {
      oneStar: 34,
      twoStar: 7,
      threeStar: 3,
      fourStar: 13,
      fiveStar: 166,
    },
    imagesCount: 7,
    imageCategories: [],
    openingHours: [
      { day: "Monday", hours: "9 AM to 6 PM" },
      { day: "Tuesday", hours: "9 AM to 6 PM" },
      { day: "Wednesday", hours: "9 AM to 6 PM" },
      { day: "Thursday", hours: "9 AM to 6 PM" },
      { day: "Friday", hours: "9 AM to 2 PM" },
      { day: "Saturday", hours: "9 AM to 2 PM" },
      { day: "Sunday", hours: "Closed" },
    ],
    additionalInfo: {
      Accessibility: [
        { "Wheelchair accessible entrance": true },
        { "Wheelchair accessible parking lot": true },
        { "Wheelchair accessible restroom": true },
      ],
      Amenities: [{ Restroom: true }],
      Planning: [{ "Appointments recommended": true }],
      Payments: [
        { "Credit cards": true },
        { "Debit cards": true },
        { "NFC mobile payments": true },
      ],
    },
    url: "https://www.google.com/maps/search/?api=1&query=Supreme%20Dental%20Associates&query_place_id=ChIJO_gNcz6rw4kRLrhzDMmCnwQ",
    searchPageUrl:
      "https://www.google.com/maps/search/orthodontist:%20West%20Orange,%20NJ?hl=en",
    searchString: "orthodontist: West Orange, NJ",
    language: "en",
    rank: 27,
    isAdvertisement: false,
    imageUrl:
      "https://lh3.googleusercontent.com/p/AF1QipNCD6F65DhvXTC7wmPoFET8ToUxyHKQfyGBJ1pX=w408-h399-k-no",
    kgmid: "/g/1tf7ynsh",
  },
];

// Website Analysis Output - Mix of good and areas needing improvement
export const MOCK_WEBSITE_ANALYSIS: WebsiteAnalysis = {
  overall_score: 84.5,
  overall_grade: "B+",
  pillars: [
    {
      category: "Trust & Authority",
      score: 72,
      key_finding:
        "⚠️ Missing patient testimonials on key landing pages. No video content found to humanize the practice. Trust signals are limited to text-only reviews. Recommend adding video testimonials and before/after galleries to boost credibility.",
      action_items: [],
    },
    {
      category: "Accessibility",
      score: 96,
      key_finding:
        "Excellent mobile responsiveness and ADA compliance. All key accessibility features properly implemented including alt tags, color contrast, and form labels. Site is fully accessible to all users.",
      action_items: [],
    },
    {
      category: "Patient Journey",
      score: 68,
      key_finding:
        "⚠️ Critical gap: No online booking integration detected. Patients must call to schedule, creating friction. FAQ section is thin with only 4 questions. Add online scheduling and expand FAQs to reduce appointment drop-off.",
      action_items: [],
    },
    {
      category: "Technical Reliability",
      score: 98,
      key_finding:
        "Excellent technical performance. SSL certificate active, page load time of 1.8 seconds is well under threshold, and all Core Web Vitals pass. Site is optimized for speed and security.",
      action_items: [],
    },
  ],
};

// GBP Analysis Output - Mix of strong areas and critical gaps
export const MOCK_GBP_ANALYSIS: GBPAnalysis = {
  gbp_readiness_score: 79.8,
  gbp_grade: "B",
  sync_audit: {
    nap_match: true,
    mismatched_fields: [
      "Minor: Business name includes ' - Dr. Garrison Copeland' suffix on GBP only",
    ],
    trust_gap_severity: "Low",
  },
  pillars: [
    {
      category: "Profile Integrity",
      score: "97",
      key_finding:
        "Excellent NAP consistency across all platforms. Address, phone, and business name are properly synchronized. Schema markup is correctly implemented on website.",
      executive_recommendation:
        "Maintain current NAP standards. Continue monitoring for any discrepancies.",
    },
    {
      category: "Trust & Engagement",
      score: "62",
      key_finding:
        "⚠️ Review volume critically low at 62 reviews vs. 825 for top competitor (D&G Dental). This 763-review gap is a significant competitive disadvantage. Response rate is good but volume is the primary concern.",
      executive_recommendation:
        "Implement aggressive review generation campaign immediately. Target 50+ new reviews per month through post-appointment SMS/email sequences.",
    },
    {
      category: "Visual Authority",
      score: "95",
      key_finding:
        "Strong visual presence with 24 high-quality images. Photos show modern equipment, clean facilities, and professional team. Regular updates detected in the past 30 days.",
      executive_recommendation:
        "Maintain monthly photo updates. Consider adding video content to further enhance engagement.",
    },
    {
      category: "Search Conversion",
      score: "71",
      key_finding:
        "⚠️ GBP Posts are active but lack strategic keyword targeting. 'Invisalign West Orange' and 'braces near me' terms underutilized. No special offers or promotions detected to drive conversions.",
      executive_recommendation:
        "Create weekly posts targeting high-intent local keywords. Add promotional offers to increase click-through rates.",
    },
    {
      category: "Competitor Analysis",
      score: "58",
      key_finding:
        "⚠️ CRITICAL: Ranking #4 in local pack behind 3 competitors with higher review counts. D&G Dental dominates with 825 reviews at 4.9 stars. Market share is being lost to better-optimized competitors.",
      executive_recommendation:
        "This is a competitive emergency. Without immediate action on review volume and GBP optimization, market position will continue to decline.",
    },
  ],
};

// Website Metadata - Additional info from the provided sample
export const MOCK_WEBSITE_METADATA: WebsiteMetadata = {
  isSecure: true,
  loadTime: 2052,
  brokenLinks: [],
  napDetails: {
    businessName: "Garrison Orthodontics",
    addresses: [
      "300 Executive Drive, Suite 365, West Orange, NJ, 07052, US",
      "300 Executive Dr. Suite 365 West Orange, NJ 07052",
    ],
    phoneNumbers: ["(862) 451-8117", "862-451-8117", "8624518117"],
    emails: ["dr.c@garrisonorthodontics.com"],
  },
};

// Screenshot images for the "Website Scan" visualization - using local public folder
export const MOCK_SCREENSHOT_DESKTOP = "/desktop.png";
export const MOCK_SCREENSHOT_MOBILE = "/mobile.png";
